### ISSUE TITLE
Library chart service accounts on apps have invalid settings

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/helm-charts#104]
I'm not sure how Service Accounts are expected to work today, or if they're not yet implemented full. The example https://github.com/replicatedhq/replicated-starter-helm/blob/89fe55aaa057cdc040b4abb3b076824d16e7ddd8/examples/determined-ai/templates/master-permissions.yaml#L2 seems to show that they aren't implemented since it's done by hand.

There is a setting on apps: https://github.com/replicatedhq/helm-charts/blob/819fd7b11c061334bb28371314d5ee12c1aa926a/charts/replicated-library/templates/lib/_apps.tpl#L22
However this calls _serviceAccount.tpl but doesn't set the necessary Context so it will always fail https://github.com/replicatedhq/helm-charts/blob/819fd7b11c061334bb28371314d5ee12c1aa926a/charts/replicated-library/templates/lib/_serviceaccount.tpl#L9

If this isn't fully implemented the check in _apps.tpl should be removed since it can never pass. If it's meant to work another way it needs to be fixed but it's not obvious to me what the other way would be. I would expect ServiceAccounts from the app api to work the same as secretes or configmaps. I would expect the field to take the name of a service account in the serviceAccounts api which the chart maps handling prefixes.

**Comment by chris-sanders** [comment]
@adamancini looks like you wrote this section, maybe you can help me understand if it's leftover and needs to be cleaned up or broken and needs to be fixed.

**Comment by adamancini** [comment]
@chris-sanders I see;  the apps.serviceAccount field existed for a bit, but I don't know if it had an implementation.  

I think I had the intention that apps.serviceAccount could wrap the "all-in-one" service account & role & rolebinding, but that isn't written yet - so I think we can probably turn this key off for now.

**Comment by chris-sanders** [comment]
Ok thanks, I'll do that just wanted to make sure I had context.
