### ISSUE TITLE
[Library] unique object names per release

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/helm-charts#20]
While I'm not yet fully understanding the various name options, it doesn't appear that we're prefixing objects in a way that will keep them unique. I would expect a chart to be able to be installed with different releases in the same namespace and I'm not initially seeing a way to do that.

Some specific examples of collisions I currently see.
* PVC name
* Service name
* Deployment name

Currently these are taking their name from the yaml file keys and I think it should include the .Relase.Name or in some fashion include one of the name overrides. What I've typically seen is to default these things to have a prefix of the release name and allow an override if you want the prefix to be set via the values file and override the Helm release.

I'm seeing this working on the wg-easy chart and the use case is that you would deploy the chart 1 per vpn configuration and I would want those all running in the same name space but with different firewall rules and overlay network configurations.

**Comment by chris-sanders** [comment]
I think I see the current design, each object can be interdependently override. I think that's a nice touch but maybe we need:

global.nameOverride: Replaces the chart name.
global.fullnameOverride: Replaces both the release and chart name.
object.nameOverride: Replaces the object name where applicable

Then you would have something like:
Service: ReleaseName-ChartName-ServiceName
PVC: RelaseName-ChartName-PVCName

So if I have PVC named `config` in a release named `release` and a chart named `chart`.

Default: relase-chart-config
Set the nameOverride: relase-nameOverride-config
Set the fullnameOverride: fullnameOverride-config
Also set the Object.nameOverride: fullnameoverride-nameOverride

This would mean that each release has unique objcets so they "just work". However, the user can adjust the prefixes to their preference and with the existing object level override even the actual object name. If we _really_ want to make it flexible I guess we could make "fullnameOverride" accept an empty object or empty string and remove the 'release' and 'chart' sections entirely.

I don't know that removing is necessary and it could be added later as non-breaking because a fullnameOverride of an empty string would be invalid anyway.

**Comment by chris-sanders** [comment]
I've also just noticed the service selectors and matching deployment objects will need labels as well.

From https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels
I think `app.kubernetes.io/instance` should be set to the ReleaseName
While we're at it I guess we could set `app.kubernetes.io/version` a well? I think we would want to set this to the tag but allow an override for it on the pod. I believe service meshes will use this for A/B and Canary deployments I'm not familiar with any stand usage of the other labels that I can think of off the top of my head.

**Comment by diamonwiggins** [comment]
Documenting here for visibility after some internal discussions that we'll very likely take this in a direction where we expose a template that takes a arbitrary name as input and generates that name with the release and/or chart names prefixed as you'd expect in most helm charts. 

eg.

`{{- include "replicated-library.generateName" "service-name" -}}`

returns

`releaseName-chartName-service-name`

This is needed in cases where users need to cross reference resources to be created in the chart.

```
<in your hardcoded values template>
apps:
  some-app:
    enabled: true
    containers:
      some-app:
        env:
          SOME_API: {{- include "replicated-library.generateName" "some-api" -}}
services:
  some-api:
    enabled: true
```

**Comment by diamonwiggins** [comment]
@drohnow if you're looking for what to pick up after the StatefulSet work, this might be interesting to you.

**Comment by chris-sanders** [comment]
@diamonwiggins do you have general thoughts of how to implement this?
I'm actually not clear between the `class` and `lib` implementations and given the number of objects that need to have a prefix if there's a "best" entry point to go about implementing this.

I see you're thinking about a generator to generate the name of specific objects too. Does that generator just take "any input" and put a prefix on it or does it care what the input is in some way? If it's just appending a prefix wouldn't just having a function that returns the prefix be clearer, or maybe having it return everything merged for you is better when you go to use it?

Without writing the whole thing if you could give some pointers on roughly what you're thinking the implementation would look like and where you would expect to see changes that would help get it scheduled.
