### ISSUE TITLE
[Library] Change app to pod in the

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/helm-charts#22]
As I'm using the chart I've just noticed that we don't use "pod" anywhere in the spec, at least not that I've seen so far. I think what we're calling `app` is actually just a pod. Given we're using `secrets`, `ingresses` and even `containers` within the `app` tag is there any reason not to use the more accurate `pod` name?

Making a clear distinction between pods and containers right in the API will help people learn the underlying concepts and probably help with day 2 if a user is talking to someone that is talking about `pods` and not `apps`

**Comment by diamonwiggins** [comment]
@chris-sanders I see what you're saying, but I think we'll want to think about anything not on the Pod spec, but actually on the controller's(deployment/daemonset/etc.) spec. For example:

```
pods:
  your-pod:
    type: deployment
```

This seems like it could be confusing. There's also the scenario of `volumes` which are global to all Pods.

**Comment by chris-sanders** [comment]
Oh yea those are good points, that abstraction isn't actually a direct 1:1 mapping like some of the other objects like `container` is. Hum, yea if we renamed it then we would actually be considering removing those abstractions and re-using something like how we map services to apps today. 

I don't know that defining a deployment and mapping it to a pod is a very good experience, I think I retract this request. I guess we could always implement that later (not like `pod` or `deployment` keys are going to get used) if we later decided that was a nice way to handle things. But I like the app abstraction today.
