### ISSUE TITLE
[Library] Break glass?

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/helm-charts#26]
I like the new documentation sections that tell you how set defaults and cross-reference values files. I've recently used them and it covered what I needed quickly and easily.

However, the naming continue to confuse me. It's labeled "Break Glass" and I just can't see how that's appropriate for what it's describing. Something like "Advanced Templating" or "Using Go functions" would seem a lot more clear to me. Break Glass seems to imply you are no longer using the chart, or you're bypassing it but you aren't doing either. These sections still describe using the Library Chart just doing so in a more advanced way.

I'm also a little curious if the phrase "Break Glass" will have any significant meaning to people who's native language isn't English. It's a turn of phrase that I'm not clear is commonly understood across cultures.

**Comment by diamonwiggins** [comment]
Agreed
