### ISSUE TITLE
[Library] Don't include example values in released charts

### ISSUE THREAD

**Issue by chris-sanders** [replicatedhq/helm-charts#36]
Currently the library chart includes a values file which is used as documentation. It provides some examples and docstrings that generate the readme. However, I just recently realized the vales are a valid values file and are shipped with the chart!

Doing some work this past week I realized I had an app named "example" as well as other components which really shouldn't be there. This might just be an exercise in organizing our documentation so there is a better place/way to document this but we do need to eventually not ship example values in all charts that use the library. At some point we're likely to cause a name collision, as well as the occasional confusion when someone notices them as I did recently.

**Comment by diamonwiggins** [comment]
Makes sense. I think what we should do is:

1. Leave `values.yaml` with the `global` and `defaults` keys. 
2. Move all example values over to a `values-example.yaml`
3. Update docs with new `helm-docs` command that passes in the `values-example.yaml` in addition to `values.yaml`. There should be a `-f` for this.

**Comment by drohnow** [comment]
Hi @diamonwiggins 
hem-docs by default will leverage the values.yaml file for docs generation. The -f flag can be used to specify a different file, however, hem-docs will only allow the use of one file.

`hem-docs .... -f values1.yaml -f values2.yaml`  
nor 
`hem-docs ... -f values1.yaml values2.yaml` 
will not provide the results we desire. 

I think the quick and dirty could be:

`cat values.yaml >> merge_values.yaml
  cat values.example.yaml >> merge_values.yaml
  helm-docs -t README.md.gotmpl -t README_CHANGELOG.md.gotmpl -t README_CONFIG.md.gotmpl -f merge_values.yaml 
  rm -rf merge_values.yaml
`

Or perhaps you may have another suggestion?

**Comment by drohnow** [comment]
@chris-sanders just realized that @diamonwiggins is on PTO today; seeing if you had any thoughts.

**Comment by chris-sanders** [comment]
@drohnow I don't love having to run 3 commands to generate the docs, although we could start using something like https://taskfile.dev/ to make regenerating docs a 1 liner still. 

The ultimate goal here is to get the examples out of values.yaml because that's actually shipped with the chart and still provide examples in documentation. Can we just use `values-example.yaml` as the values file for helm-docs and let `values.yaml` be just defaults and not part of documentation?

**Comment by drohnow** [comment]
@chris-sanders I really like the taskfile.dev option; just tested it out and works well.  I will gen up and submit PR if all is amenable to this approach.

**Comment by chris-sanders** [comment]
While I like taskfile it is another dependency, are you going down that route b/c my suggestion of just keeping the examples in a different yaml files doesn't work for some reaon?

**Comment by drohnow** [comment]
Taskfile...yes, bc I think it is a clean way of doing it.

My thought about updating README with only the values-example.yaml is that when we update global and default values, then we will need to make sure that we update two files (values-example.yaml and values.yaml); my worry is that having to remember to update in two places would let itself to be error prone.
